#spring.graphql.graphiql.enabled=true
#spring.graphql.cors.allowed-origins=*
#spring.graphql.schema.printer.enabled=true
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.database=moviedb
#spring.data.mongodb.port=27017
#spring.data.mongodb.host=localhost
#spring.data.mongodb.auto-index-creation=true
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
